### ISSUE TITLE
Add logic for request users to join company

### ISSUE THREAD

**Issue by sls-lnluksa** [sls-lnluksa/work_time_tracker#16]
Company admins should have form where they can search employees (users) by
name, email, personal_number
Admins can search by personal id, but that record should not be displayed in any results.
That is sensitive data and it has to be entered fully.

For other he can search by partly entered name or email.

From this page, company admin can request from employ to join company, but employee has to accept it.

**Comment by IvanPavlovic92** [comment]
There should be a list of all employees for current company.
When you search for employee it should not show people who are already employed in current company.
