### ISSUE TITLE
Make logic for sign_in/sing_out

### ISSUE THREAD

**Issue by sls-lnluksa** [sls-lnluksa/work_time_tracker#2]
By sign in/out we consider form which will create record of start working and end working.

Create table time_tables.
This table should contain 
```id, start_time, end_time, user_id, company_id, approved, multi_record, duration, total_minutes```

When user start with work, he should press sign in button and populate 
```id, start_time, user_id, company_id```
if there is no record for for that day, or there is records for that day but he have already sign out.
In other cases next time when he press sign out button, we should populate only end_time.

When user login he should see list of days that he has been working in current month.

**Comment by Baxxx** [comment]
Add columns `approved_start` and `approved_end` to `time_tables` table, which are set upon company admin approving.
